name: Mad Money Recommendation Scraper

on:
  push:
    paths:
      - .github/workflows/scraper.yml
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '0 0 * * *' # Run this workflow every day at 00:00

jobs:
  scheduled:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Script execution
      run: |-
        python scrape_mad_money.py -o mad_money_recommendations.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add mad_money_recommendations.csv
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

